//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aksztofa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("aksztofa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa01 {
            get {
                object obj = ResourceManager.GetObject("akasztofa01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa02 {
            get {
                object obj = ResourceManager.GetObject("akasztofa02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa03 {
            get {
                object obj = ResourceManager.GetObject("akasztofa03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa04 {
            get {
                object obj = ResourceManager.GetObject("akasztofa04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa05 {
            get {
                object obj = ResourceManager.GetObject("akasztofa05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa06 {
            get {
                object obj = ResourceManager.GetObject("akasztofa06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa07 {
            get {
                object obj = ResourceManager.GetObject("akasztofa07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa08 {
            get {
                object obj = ResourceManager.GetObject("akasztofa08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa09 {
            get {
                object obj = ResourceManager.GetObject("akasztofa09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa10 {
            get {
                object obj = ResourceManager.GetObject("akasztofa10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofa11 {
            get {
                object obj = ResourceManager.GetObject("akasztofa11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap akasztofadefault {
            get {
                object obj = ResourceManager.GetObject("akasztofadefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zsiráf
        ///egér
        ///hangya
        ///pók
        ///csirke
        ///hattyú
        ///oroszlán
        ///gepárd
        ///puma
        ///sas
        ///víziló
        ///antilop.
        /// </summary>
        internal static string allat {
            get {
                return ResourceManager.GetString("allat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ádám
        ///béla
        ///lászló
        ///bálint
        ///krisztián
        ///istván
        ///emánuel
        ///fanni
        ///zsófia
        ///erika
        ///krisztina.
        /// </summary>
        internal static string keresztnev {
            get {
                return ResourceManager.GetString("keresztnev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alma
        ///birs
        ///cseresznye
        ///egres
        ///eper
        ///görögdinnye
        ///kajszibarack
        ///kivi
        ///körte
        ///málna
        ///meggy
        ///naspolya
        ///őszibarack
        ///ribizli.
        /// </summary>
        internal static string noveny {
            get {
                return ResourceManager.GetString("noveny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kalapács
        ///csavarhúzó
        ///kés
        ///olló
        ///hangszóró
        ///monitor
        ///laptop
        ///tablet
        ///telefon
        ///asztal
        ///szék
        ///ablak
        ///ajtó.
        /// </summary>
        internal static string targy {
            get {
                return ResourceManager.GetString("targy", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tux {
            get {
                object obj = ResourceManager.GetObject("tux", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
